-- Categorias de productos (generado del CSV, 176 productos)
create table if not exists public.categorias (
  producto text primary key,
  categoria text not null check (categoria in ('Envases','Consumibles','Materias Primas')),
  updated_at timestamptz not null default now()
);
alter table public.categorias enable row level security;
drop policy if exists p_categorias_read on public.categorias;
create policy p_categorias_read on public.categorias for select using (auth.role()='authenticated');
drop policy if exists p_categorias_write on public.categorias;
create policy p_categorias_write on public.categorias for all using (public.is_admin()) with check (public.is_admin());

insert into public.categorias (producto,categoria) values
  ('Acetato de Butilo','Materias Primas'),
  ('Acetato de Butilo B1 L','Materias Primas'),
  ('Acido Clorhidrico','Materias Primas'),
  ('Acido Clorhidrico x kg','Materias Primas'),
  ('Acido Sulfonico 99 % TYPOL Labrex 200','Materias Primas'),
  ('Acrypol','Materias Primas'),
  ('Agua Desionizada','Materias Primas'),
  ('Agua destilada (Radiadores)','Materias Primas'),
  ('Aguarras','Materias Primas'),
  ('Alcohol Cereales 96° - Bioetanol','Materias Primas'),
  ('Alcohol Isopropilico','Materias Primas'),
  ('Alcohol Isopropilico x L','Materias Primas'),
  ('Alcohol Rectificado 95 %','Materias Primas'),
  ('Anfoteina','Materias Primas'),
  ('Anfoteina (Betaina de coco)','Materias Primas'),
  ('Azosoft (Base suavizante)','Materias Primas'),
  ('Bicarbonato de Sodio B.25Kg','Materias Primas'),
  ('Bidon PEAD Natural Pesado x 10 L (400 g) c/ tapa 43 m','Envases'),
  ('Bidon PEAD Natural Pesado x 10 L (400 g) c/ tapa 43 mm','Envases'),
  ('Bidones x 10 L','Envases'),
  ('Bidones x 5 L','Envases'),
  ('Blanqueador Optico','Materias Primas'),
  ('Bocha Medidora Jabon Liquido','Materias Primas'),
  ('Bolsa Reutilizable 45 x 60/70 C/Diseño PROlimpio','Envases'),
  ('Bolsas de nylon para botella de alcohol 25x30','Envases'),
  ('Bolsita Aromatización 7 X 15','Materias Primas'),
  ('Botella 1 L DURA','Envases'),
  ('Botella 60 cc con rociador (regalo tubo corto)','Envases'),
  ('Botella anillada natural 1 L Clasica','Envases'),
  ('Botella anillada natural 500 mL Clasica','Envases'),
  ('Botella C/ Serigrafia A. Eucaliptado PET 1L','Envases'),
  ('Botella C/ Serigrafia A. Rectificado PET 1L','Envases'),
  ('Botella PET  x 120 ml. C/ spray 24 blanco (calzado)','Envases'),
  ('Botella Pet 250 mL Jabon espuma C385','Envases'),
  ('Botella Pet ambar 1 L','Envases'),
  ('Botella Pet ambar 500 mL','Envases'),
  ('Botella PET ambar 500 ml (para vender kit)','Envases'),
  ('Botella PET ambar 500 ml con Valvula','Envases'),
  ('Botella Pet ambar 500ml c/valvula (kit)','Envases'),
  ('Botella PET Cuadrada x 1,5 L','Envases'),
  ('Botella Pet x 1 L Petiza','Envases'),
  ('Botella Pet x 1 L Petiza VERDE','Envases'),
  ('Botella Pet x 500 mL Cilindrica','Envases'),
  ('Botella Pet x 500 mL Cilindrica  VERDE','Envases'),
  ('Botella termo PEAD blanca de 1 L (95 g) con tapa de 43 mm','Envases'),
  ('Botella Termo PEAD Blanco x 1 L (95 g) c/ tapa 43 mm','Envases'),
  ('Botella VIDRIO Piramidal x 100 ml.','Envases'),
  ('Botellas x 2 Lts ( Blancas )','Envases'),
  ('BTC 80','Materias Primas'),
  ('Butilglicol','Materias Primas'),
  ('Carbonato de Calcio (Pulidor)','Materias Primas'),
  ('Carton Bolsita de aromatizacion (VER STOCK 15/05/24)','Consumibles'),
  ('Ceniza de soda (PH+)','Materias Primas'),
  ('Cera natural de Abejas','Materias Primas'),
  ('Cera QTE','Materias Primas'),
  ('Cintas Ph Fabricacion','Consumibles'),
  ('Clarificador Comun x 1 L','Materias Primas'),
  ('Clarificador PLUS x 1 L','Materias Primas'),
  ('Cloro Granulado','Materias Primas'),
  ('Cloro Shock','Materias Primas'),
  ('Cloruro de calcio (Absorbe Humedad)','Materias Primas'),
  ('Colorante Amarillo oil','Materias Primas'),
  ('Colorante Amarillo Tartracine en polvo','Materias Primas'),
  ('Colorante Azul Brillante en polvo','Materias Primas'),
  ('Colorante Azul Oil','Materias Primas'),
  ('Colorante Liquido Azul MP - Liquitint blue MC','Materias Primas'),
  ('Colorante Rojo oil','Materias Primas'),
  ('Colorante Rojo Punceau en polvo','Materias Primas'),
  ('Colorante Rosa Pura ( fluor )','Materias Primas'),
  ('Creolina','Materias Primas'),
  ('Desengrasate Naranja','Materias Primas'),
  ('Dietanolamina de coco','Materias Primas'),
  ('Dietilenglicol','Materias Primas'),
  ('Dipropilenglicol','Materias Primas'),
  ('DOYPACK BLANCO JACUZZI C/Z 125*70*185','Consumibles'),
  ('DOYPACK POUCH PET/PE70 105X110','Consumibles'),
  ('DOYPACK POUCH PET/PEBCO70 105*110','Consumibles'),
  ('DOYPACK TRANSPARENTE C/Z 125*70*185','Consumibles'),
  ('DOYPACK TRANSPARENTE C/Z 160*90*225','Consumibles'),
  ('DOYPACK TRANSPARENTE C/Z 200*80*250','Consumibles'),
  ('EDTA Tetrasodico','Materias Primas'),
  ('Envase PET 100 cc ( esencias )','Envases'),
  ('Envase Pet de 60cc limpia notebooks (tubo largo)','Envases'),
  ('Envase PET x 250 mL (textiles)','Envases'),
  ('Envase Unicornio 30 mL Bajo Transparente','Envases'),
  ('Enzurlan 7 moles','Materias Primas'),
  ('Esencia Ashley CAPS','Materias Primas'),
  ('Esencia Citronella','Materias Primas'),
  ('Esencia Eucalipto','Materias Primas'),
  ('Esencia Flower Beauty (10120) (MP x Kg)','Materias Primas'),
  ('Esencia Orange Blossom (10118) (MP x Kg)','Materias Primas'),
  ('Esencia Secret Wishper () (MP x Kg)','Materias Primas'),
  ('Esencia Suavex','Materias Primas'),
  ('Esencia Tea Level () (MP x Kg)','Materias Primas'),
  ('Etiq. Chicas ( COD. 2323140 ) 100 x 55 mm','Consumibles'),
  ('Etiq. Logo (COD. 22020520 ) 76 mm (2000 x R.)','Consumibles'),
  ('Etiq. Medianas corto ( COD 232246) 102 x 78 mm (1930 x R)','Consumibles'),
  ('Etiq. Medianas largo ( COD 232247) 102 x 78 mm (5000 x R)','Consumibles'),
  ('Etiq. Mini ( COD. 231093 ) 50 x 25 mm','Consumibles'),
  ('Etiqueta GRANDE BLANCA (100 x 100) ( 231078) 1500 UNIDAD/rollo','Consumibles'),
  ('Etiqueta GRANDE NUEVA (100 x 117) ( 232238 )','Consumibles'),
  ('Euperlan HCO (Opacador)','Materias Primas'),
  ('FILM ( PALLET ) x KILO  Blanco DE 50 CMS-500 MT-MIC (23 micras)','Consumibles'),
  ('FILM ( PALLET ) x KILO  DE 50 CMS-500 MT-MIC (23 micras)','Consumibles'),
  ('Film Stretch 15 micras 500 mm preestiro 300% Automatico','Consumibles'),
  ('Fluido DC/200 Y PMX200-350cs (Aceite de silicona)','Materias Primas'),
  ('Formol','Materias Primas'),
  ('Frasco Ambar con tapa 30 cc','Envases'),
  ('Frasco Auto 8 mL Cuadrado','Envases'),
  ('Frasco Pet 250 mL ( J.Manos )','Envases'),
  ('Fungozur B70DM','Materias Primas'),
  ('Gatillo Pulverizador Comun rosca 28','Envases'),
  ('Gatillo Pulverizador Comun rosca 28 CORTA','Envases'),
  ('Glicerina','Materias Primas'),
  ('Glutaraldehido','Materias Primas'),
  ('Hipoclorito de Sodio 100 grs/Lt (Materia Prima)','Materias Primas'),
  ('Hipoclorito de Sodio 100grs/Lt','Materias Primas'),
  ('Jabon en polvo x 3 kg PROlimpio','Materias Primas'),
  ('Less 27 % (Materia Prima)','Materias Primas'),
  ('Metabisulfito ( PH-)','Materias Primas'),
  ('Naftalina','Materias Primas'),
  ('No- ionico','Materias Primas'),
  ('Oxi activo','Materias Primas'),
  ('Oxi activo  (110 x piso aproxi)','Materias Primas'),
  ('Paradicloro Embolillado','Materias Primas'),
  ('Parafina','Materias Primas'),
  ('Parche P/Piscina Sin Vaciar 20 x 20cm C/Pegamento','Consumibles'),
  ('Pastilla Cloro 20 g. Cisterna (MP) Ingresar x KG','Materias Primas'),
  ('Pastilla Cloro Jacuzzi 50 gr (x 1Kg)','Materias Primas'),
  ('Pastilla Triple Accion','Materias Primas'),
  ('Pastilla Triple Accion (3 unidades)','Materias Primas'),
  ('Pastillas Cloro Cisterna 50 Grs','Materias Primas'),
  ('Pastillas Cloro JACUZZI 50 Grs','Materias Primas'),
  ('Percarbonato de Sodio','Materias Primas'),
  ('Perlante 80 %','Materias Primas'),
  ('Peroxido Hidrogeno 200 Vol (Agua Oxigenada)','Materias Primas'),
  ('Pigmento Negro Cera','Materias Primas'),
  ('Pigmento Rojo Cera','Materias Primas'),
  ('Pote 1 Kg','Envases'),
  ('Pote 250 g','Envases'),
  ('Pote 4 Kg','Envases'),
  ('Pote 500 g','Envases'),
  ('Propilenglicol (A. Radiador)','Materias Primas'),
  ('Ribon 110mm x 300 mm Cera ( COD: 353043 )','Consumibles'),
  ('Ribon Nueva 110 x 600 mts.','Consumibles'),
  ('Ribon Resina INKANTO AXR7 110 X 300 Negro (COD. 3520450)','Consumibles'),
  ('Sal Fina Yodada','Materias Primas'),
  ('Sal Purificadora P/ Piscinas X 25 Kg ST','Materias Primas'),
  ('Silicona BRB Sempure 35','Materias Primas'),
  ('Silicona S7 (Anti-espuma)','Materias Primas'),
  ('Soda en Perlas 99%','Materias Primas'),
  ('Talco Industrial P / Piscinas','Materias Primas'),
  ('Tapas Alcoa azul rosca 28','Envases'),
  ('Tapas Alcoa azul rosca 28/400','Envases'),
  ('Tapas Alcoa rosca 28','Envases'),
  ('Tapas Alcoa rosca 28 CORTA','Envases'),
  ('Tapas Alcoa Rosca 28 corta','Envases'),
  ('Tapas Alcoa verde rosca 28','Envases'),
  ('Tapas Alcoa verde rosca 28/400','Envases'),
  ('Tapas Flip Top TFT (iniciador de fuego) rosca 28','Envases'),
  ('Tapas Flip Top TFT (iniciador de fuego) rosca 28/400','Envases'),
  ('Tapas Flip Top TFT (iniciador de fuego) rosca 28/410','Envases'),
  ('Tira probador perfume x 2000','Materias Primas'),
  ('Tirillas 1kg (350 Unid)','Consumibles'),
  ('Trietanolamina','Materias Primas'),
  ('Trietanolamina 99%','Materias Primas'),
  ('Tubo Kraft 5 diámetro x 16 alto','Consumibles'),
  ('Valvula Crema  rosca 28','Envases'),
  ('Valvula Crema  rosca 28 /400 corta','Envases'),
  ('Valvula Crema  rosca 28 /410','Envases'),
  ('Valvula Espumadora ( JEV )','Envases'),
  ('Valvula rosca 28 negra (para Kit)','Envases'),
  ('Varitas de ratan (1 Kg: 1300 Unid)','Consumibles'),
  ('Vaselina','Materias Primas'),
  ('Verde Liquido Oscuro','Materias Primas'),
  ('Vermiculita','Materias Primas')
on conflict (producto) do update set categoria=excluded.categoria, updated_at=now();
