-- ============================================================
--  SEED Importacion: 119 articulos (hojas Articulos/Enjoy/Intex).
--  Correr DESPUES de imp_schema.sql. Idempotente: recarga articulos
--  y su stock base. NO toca pallets ni movimientos.
--  Clave de correlacion: (proveedor, descripcion) -- unica y no nula.
-- ============================================================
begin;
delete from public.imp_stock;
delete from public.imp_articulos;

with datos(proveedor,codigo,descripcion,tipo,un_x_caja,st_artigas,st_furriol) as (values
  ('Subatir','220029','Botella PET  x 120 ml. C/ spray 24 blanco (calzado) (24.2g)','Consumo',null,null,null),
  ('Subatir','220034','Botella PET x 250 ml con Gatillo Mini trigger (Textiles) (37.3g)','Consumo',360,null,12160),
  ('Subatir','220031','Botella PETx 100 ml.  (esencias Green Oil) (16.1g)','Consumo',494,null,11220),
  ('Subatir','490166','CAJA P/Kit Mopa Centrifuga','Venta',null,null,null),
  ('Subatir','490167','CAJA P/Kit Mopa Plana Autolimpiante','Venta',null,null,null),
  ('Subatir','220210','Envase Unicornio 30 mL Bajo Transparente (8.8g)','Consumo',2000,null,9767),
  ('Subatir','490115','Equipo Aromatizador PRL Fun elct/pila  (blanco)','Venta',null,null,null),
  ('Subatir','490116','Equipo Aromatizador PRL Fun elct/pila  (Negro)','Venta',null,null,null),
  ('Subatir','490079','Estanteria Picking Chapa Estante 2m x 60cm (x unidad )','Infraestructura',null,null,null),
  ('Subatir','490078','Estanteria Picking Parante 2m x unidad (por  unidad)','Infraestructura',null,null,null),
  ('Subatir','490002','Estanteria Picking Pata Lateral (Portico) 2m x 60cm (x unidad)','Infraestructura',null,null,null),
  ('Subatir','220208','Frasco Auto 8 mL Cuadrado','Consumo',null,null,null),
  ('Subatir','220028','Frasco VIDRIO ambar x 30 ml. c/tapa y gotero (48.3g)','Consumo',330,null,9830),
  ('Subatir','220106','Gatillo Mini Trigger rosca 24','Consumo',1000,null,36400),
  ('Subatir','220105','Gatillo Pulverizador Comun rosca 28','Consumo',500,null,49900),
  ('Subatir','490208','Hornito Chico CELESTE (Sky Blue) (Subatir)','Venta',null,null,null),
  ('Subatir','490192','Hornito Chico ROSA (Subatir)','Venta',null,null,null),
  ('Subatir','490209','Hornito Chico VERDE (Green) (Subatir)','Venta',null,null,null),
  ('Subatir','490210','Hornito Chico VERDE OSCURO (Dark Green) (Subatir)','Venta',null,null,null),
  ('Subatir','490193','Hornito Grande C/ Soporte GRIS (Subatir)','Venta',null,null,null),
  ('Subatir','490207','Hornito Grande C/ Soporte NEGRO (Black) (Subatir)','Venta',null,null,null),
  ('Subatir','490191','Hornito Madera - Ceramica (Subatir)','Venta',null,null,null),
  ('Subatir','490190','Hornito Mediano C/ Soporte (Subatir)','Venta',null,null,null),
  ('Subatir','490187','Humidifer Modelo 1 220 mL SD05','Venta',null,1331,null),
  ('Subatir','490188','Humidifer Modelo 2 330 mL SD07','Venta',null,null,null),
  ('Subatir','490159','Kit Escoba Y Pala Plegable (Subatir)','Venta',15,40,135),
  ('Subatir','490156','Kit Mopa Centrifuga + Balde + 2 Repuestos (Subatir)','Venta',null,null,null),
  ('Subatir','490200','Kit Mopa Centrifuga + Balde + 2 Repuestos /Ruedas (Subatir) v02','Venta',20,null,280),
  ('Subatir','490157','Kit Mopa Plana Autolimpiante Con  Balde + 2 Repuestos (Subatir)','Venta',24,24,null),
  ('Subatir','490158','Kit Mopa Spray (Subatir)','Venta',null,null,null),
  ('Subatir','490205','Kit Mopa Spray NUEVO - r40x12 (Subatir) v02','Venta',null,null,null),
  ('Subatir','490198','Mecha Repuesto Humidifer 11mm','Venta',null,null,null),
  ('Subatir','490189','Mecha Repuesto Humidifer 8.5 mm','Venta',null,null,null),
  ('Subatir','490202','Repuesto Cabezal 2 Mopa Centrifuga C/Ruedas (Subatir) v02','Venta',null,null,null),
  ('Subatir','490165','Repuesto Cabezal Mopa Centrifuga (Subatir)','Venta',null,null,null),
  ('Subatir','490164','Repuesto Cabo Mopa Centrifuga (Subatir)','Venta',null,null,null),
  ('Subatir','490203','Repuesto Cabo Mopa Centrifuga C/ruedas (Subatir) v02','Venta',null,28,null),
  ('Subatir','490206','Repuesto Mopa Centrifuga C/Ruedas (Subatir)  v02','Venta',null,79,null),
  ('Subatir','490160','Repuesto Mopa Plana Autolimpiante (Subatir)','Venta',null,null,null),
  ('Subatir','490163','Repuesto Mopa Redonda Centrifuga (Subatir)','Venta',null,95,null),
  ('Subatir','490161','Repuesto Mopa Spray (Subatir)','Venta',null,null,null),
  ('Subatir','490204','Repuesto Mopa Spray NUEVO 40x12cm  (Subatir) v02','Venta',null,null,null),
  ('Subatir','490201','Repuesto Tambor  Mopa Centrifuga C/Ruedas (Subatir) v02','Venta',null,60,null),
  ('Subatir','490162','Repuesto Tambor Mopa Centrifuga (Subatir)','Venta',null,null,null),
  ('Subatir','220132','Tapas Alcoa Rosca 28 (Caja - 3000 Uni)','Consumo',5000,null,47660),
  ('Subatir','220177','Tapas Alcoa Rosca 28 CORTA','Consumo',null,null,null),
  ('Subatir','220209','Tubo Kraft 5 diámetro x 16 alto','Consumo',360,null,1650),
  ('Subatir','220135','Valvula Crema Jabon De Mano  rosca 28','Consumo',null,null,null),
  ('Subatir','220137','Varita de Ratan x 1 unidad ( 1300 x Kilo )','Consumo',null,null,null),
  ('Subatir','220040','Botella Vidrio Piramidal x 100 ml','Consumo',70,null,16200),
  ('Enjoy','490080','Aspirador Oval Plastico CEPILLO (Subatir)',null,null,null,null),
  ('Enjoy','490081','Cepillo Plastico 26cm (10p) (Subatir)',null,null,null,null),
  ('Enjoy','490082','Cepillo Curvo 46cm Plastico (Subatir)',null,null,null,null),
  ('Enjoy','490083','Cepillo Curvo 46cm Metal (Subatir)',null,null,null,null),
  ('Enjoy','490084','Recoge Hojas Plano Estandar (Subatir)',null,null,null,78),
  ('Enjoy','490085','Recoge Hojas Profesional C/Bolsa Cuadrado (Subatir)',null,null,null,null),
  ('Enjoy','490086','Pertiga Alumino 2,4 M (Subatir)',null,null,null,null),
  ('Enjoy','490087','Pertiga Alumino 4,8 M (Subatir)',null,null,null,65),
  ('Enjoy','490088','Manguera 9 M (Subatir)',null,null,null,7),
  ('Enjoy','490089','Boyas 3 Pastillas (Subatir)',null,null,null,100),
  ('Enjoy','490091','Termometro Piscina Deluxe (Subatir)',null,null,null,174),
  ('Enjoy','490092','Aspiradora 8 Ruedas C/Giratoria (Subatir)',null,null,null,null),
  ('Enjoy','490094','Aspiradora JET P/Manguera (Subatir)',null,null,null,null),
  ('Enjoy','490095','Kit Aspiradora P/Estructural-Bomba Eco (Subatir)',null,null,null,null),
  ('Enjoy','490096','Recoge Hojas Plano C/Pertiga 1,20 M (Subatir)',null,null,null,null),
  ('Enjoy','490097','Manguera 7,5 M (Subatir)',null,null,null,null),
  ('Enjoy','490098','Filtro Tipo 1 Generico (Subatir)',null,null,null,null),
  ('Enjoy','490099','Filtro Tipo 2 Generico (Subatir)',null,null,null,null),
  ('Enjoy','490100','Aspiradora De Aluminio 34.5 Cm (Subatir)',null,null,null,null),
  ('Enjoy','490101','Boya Dispensador Chico 12.6 Cm (Subatir)',null,null,null,1),
  ('Enjoy','490102','Kit PH Y CL Liquido (Subatir)',null,null,null,null),
  ('Enjoy','490103','Filtro SPA Compatible Multimarcas (Subatir)',null,null,null,null),
  ('Enjoy','490104','Recoge Hojas Profesional Plano Cuadrado (Subatir)',null,null,null,null),
  ('Enjoy','490105','Manguera C/ Terminales 15 M (Subatir)',null,null,null,null),
  ('Enjoy','490106','Aspiradora Articulada Aluminio 35 Cm',null,null,null,null),
  ('Enjoy','490107','Test Sal x 10 Unidades (Subatir)',null,null,null,null),
  ('Enjoy','490171','Test Cloro, PH y Alcalinidad total (Subatir)',null,null,null,null),
  ('Enjoy','490172','Cepillo Esquinero P/ Piscinas (Subatir)',null,null,null,3),
  ('Enjoy','490177','Flota Flota Amarillo',null,null,24,288),
  ('Enjoy','490178','Flota Flota azul',null,null,24,264),
  ('Enjoy','490179','Flota Flota Verde',null,null,24,264),
  ('Enjoy','490180','Puntero de Manguera 1 1/2 pulgadas',null,null,null,null),
  ('Enjoy','490181','Flota Flota Rojo',null,null,24,336),
  ('Enjoy',null,'Repuestos  - 19 ruedas',null,null,null,null),
  ('Enjoy',null,'Repuestos  - 20 bolsitas para aspiradora JET',null,null,null,null),
  ('Enjoy',null,'Repuestos - Mariposa Clip x 3 unidades',null,null,null,null),
  ('Intex','490039','Bomba de Arena 7900 Lts / Hr IM/INTX',null,null,null,null),
  ('Intex','490040','Bomba Filtrado 3785 Lts/hr Filtro A IM/INTX',null,null,null,null),
  ('Intex','490041','Cobertor Easy Set 305 (Aro) IM/INTX',null,null,null,6),
  ('Intex','490042','Cobertor Easy Set 366 (Aro) IM/INTX',null,null,null,12),
  ('Intex','490043','Cobertor Easy Set 457(Aro) IM/INTX',null,null,null,5),
  ('Intex','490044','Cobertor Metal Frame 305 cm (Estructural) IM/INTX',null,null,null,null),
  ('Intex','490045','Cobertor Metal Frame 366 cm (Estructural) IM/INTX',null,null,null,null),
  ('Intex','490046','Cobertor Metal Frame 457 cm (Estructural) IM/INTX',null,null,null,null),
  ('Intex','490047','Cobertor Solar 305 cm (290 cm) IM/INTX',null,null,null,null),
  ('Intex','490048','Cobertor Solar 366 cm (348 cm) IM/INTX',null,null,null,null),
  ('Intex','490049','Cobertor Solar 457cm (448 cm) IM/INTX',null,null,null,null),
  ('Intex','490050','Escalera hasta 91 cm de altura IM/INTX',null,null,null,null),
  ('Intex','490051','Escalera hasta 122 cm de altura IM/INTX',null,null,null,null),
  ('Intex','490052','Filtro H Intex IM/INTX',null,null,null,null),
  ('Intex','490053','Filtro A Intex IM/INTX',null,null,null,null),
  ('Intex','490054','Kit de Limpieza DELUXE INTEX ref. 28003/58959 IM/INTX',null,null,null,15),
  ('Intex','490055','Kit de Mantenimiento piscinas ref.28002/58958 IM/INTX',null,null,null,null),
  ('Intex','490056','Manguera individual INTEX 32 x150 IM/INTX',null,null,null,null),
  ('Intex','490057','Lava pie IM/INTX',null,null,null,null),
  ('Intex','490058','Pertiga telescopica 2,79 cm IM/INTX',null,null,null,null),
  ('Intex','490059','Adaptador especial rosca/manguera IM/INTX',null,null,null,6),
  ('Intex','490062','Pelota Inflable Intex 3+ años IM/INTX',null,null,null,24),
  ('Intex','490064','Colchoneta color Intex IM/INTX',null,null,null,null),
  ('Intex','490069','Rosca Flot. Neumatico Intex 9+ años IM/INTX',null,null,null,null),
  ('Intex','490070','Rosca Flot. Estrellas Intex 9+ años IM/INTX',null,null,null,null),
  ('Intex','490072','Lente agua Colores Intex 3 a 8 años IM/INTX',null,null,null,36),
  ('Intex','490073','Lentes Agua Sport 14 años INTEX IM/INTX',null,null,null,null),
  ('Intex','490074','Piscina Bebe 86*25 1-3 años IM/INTX',null,null,null,null),
  ('Intex','490108','zzAspiradora De Mano Recargable IM/INTX',null,null,null,null),
  ('Intex','490109','Colchoneta Con Respaldo IM/INTX',null,null,null,null),
  ('Intex','490110','Inflable Cocodrilo IM/INTX',null,null,null,null),
  ('Intex','490111','Inflable Delfin IM/INTX',null,null,null,null),
  ('Intex','490112','Juego Buceo ALGAS IM/INTX',null,null,null,null)
)
, ins as (
  insert into public.imp_articulos(proveedor,codigo,descripcion,tipo,un_x_caja)
  select proveedor,codigo,descripcion,tipo,un_x_caja from datos
  returning id, proveedor, descripcion
)
insert into public.imp_stock(articulo_id, deposito, cantidad)
select i.id, d.dep, d.cant
from ins i
join datos x on x.proveedor = i.proveedor and x.descripcion = i.descripcion
cross join lateral (values ('Furriol', coalesce(x.st_furriol,0)), ('Artigas', coalesce(x.st_artigas,0))) as d(dep,cant);
commit;
